server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 3000
      min-spare: 1000

spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/main/
    suffix: .html

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dev_replica
    username: replica_user
    password: replica_pass!2#

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    open-in-view: false
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
